version: '3.4'

services:
  sqlServer:
    image: mcr.microsoft.com/mssql/server
    container_name: healthfood_db
    environment:
      SA_PASSWORD: "A123456@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: aguiar
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
  howtodevelop.healthfood.webapp:
    image: ${DOCKER_REGISTRY-}howtodevelophealthfoodwebapp
    build:
      context: .
      dockerfile: src/HowToDevelop.HealthFood.WebApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIROMENT=Development
    depends_on:
      - sqlServer
      - mongodb